"use strict"

const ManagedSkills = require("../../kernel/managed_skills")

const LAUNCHER_AGENT_FILES = [
  "AGENTS.md",
  "CLAUDE.md",
  "GEMINI.md",
  "QWEN.md",
  ".windsurfrules",
  ".cursorrules",
  ".clinerules"
]

const LAUNCHER_GIT_EXCLUDE_ENTRIES = [
  "/logs",
  "/cache",
  "/AGENTS.md",
  "/CLAUDE.md",
  "/GEMINI.md",
  "/QWEN.md",
  "/SPEC.md",
  "/REQUEST.md",
  "/.geminiignore",
  ".clinerules",
  ".cursorrules",
  ".windsurfrules"
]

const LAUNCHER_FOLDER_CONTEXT_PREAMBLE = [
  "# Folder Context",
  "",
  "Before acting in this folder:",
  "1. If `REQUEST.md` exists, read it first. It contains the latest request for this run.",
  "2. If `SPEC.md` exists, read it next. It describes the long-term purpose of this folder.",
  "3. If they conflict, follow `REQUEST.md` for the current run while preserving the broader intent in `SPEC.md`."
].join("\n")

const createLauncherInstructionBootstrap = ({ kernel, fs, path, os }) => {
  const resolvePinokioBody = async () => {
    return ManagedSkills.readEnabledManagedSkillBody(kernel, "pinokio").catch(() => "")
  }

  const resolveGepetoBody = async () => {
    return ManagedSkills.readEnabledManagedSkillBody(kernel, "gepeto").catch(() => "")
  }

  const buildLauncherInstructionBody = async () => {
    const pinokioBody = (await resolvePinokioBody()).trim()
    const gepetoBody = (await resolveGepetoBody()).trim()
    const sections = []

    if (pinokioBody) {
      sections.push(["## Pinokio", "", pinokioBody].join("\n"))
    }
    if (gepetoBody) {
      sections.push(["## Gepeto", "", gepetoBody].join("\n"))
    }

    if (sections.length === 0) {
      return ""
    }

    return [
      LAUNCHER_FOLDER_CONTEXT_PREAMBLE,
      "",
      "# Pinokio Launcher Instructions",
      "",
      "This file is generated by Pinokio for launcher-created folders.",
      "",
      sections.join("\n\n")
    ].join("\n").trim() + "\n"
  }

  const ensureLauncherAgentFile = async (filepath, content) => {
    let existing = ""
    try {
      existing = await fs.promises.readFile(filepath, "utf8")
    } catch (error) {
      if (!(error && error.code === "ENOENT")) {
        throw error
      }
    }
    if (!existing) {
      await fs.promises.writeFile(filepath, content, "utf8")
      return true
    }
    const normalizedExisting = String(existing || "")
    const looksLikePreviousGeneratedBody = normalizedExisting.startsWith("# Pinokio Launcher Instructions")
    const alreadyHasFolderContext = normalizedExisting.startsWith("# Folder Context")
    if (looksLikePreviousGeneratedBody && !alreadyHasFolderContext) {
      await fs.promises.writeFile(filepath, content, "utf8")
      return true
    }
    return false
  }

  const ensureGeminiIgnore = async (rootPath) => {
    const geminiIgnorePath = path.resolve(rootPath, ".geminiignore")
    const content = [
      "!/logs",
      "!/GEMINI.md",
      "!/SPEC.md",
      "!/REQUEST.md",
      "!/app",
      `!${kernel && kernel.homedir ? kernel.homedir : os.homedir()}`
    ].join("\n")
    let existing = ""
    try {
      existing = await fs.promises.readFile(geminiIgnorePath, "utf8")
    } catch (error) {
      if (!(error && error.code === "ENOENT")) {
        throw error
      }
    }
    if (existing === content) {
      return false
    }
    await fs.promises.writeFile(geminiIgnorePath, content, "utf8")
    return true
  }

  const writeLauncherPromptContextFiles = async (rootPath, options = {}) => {
    const targetPath = path.resolve(rootPath)
    await fs.promises.mkdir(targetPath, { recursive: true })

    const spec = typeof options.spec === "string" ? options.spec.trim() : ""
    const request = typeof options.request === "string" ? options.request.trim() : ""
    const wrote = []

    if (spec) {
      await fs.promises.writeFile(path.resolve(targetPath, "SPEC.md"), `${spec}\n`, "utf8")
      wrote.push("SPEC.md")
    }

    if (request) {
      await fs.promises.writeFile(path.resolve(targetPath, "REQUEST.md"), `${request}\n`, "utf8")
      wrote.push("REQUEST.md")
    }

    return {
      ok: true,
      files: wrote
    }
  }

  const ensureGitExcludeEntries = async (rootPath) => {
    const gitDir = path.resolve(rootPath, ".git")
    const gitStat = await fs.promises.stat(gitDir).catch(() => null)
    if (!gitStat) {
      return false
    }
    const excludePath = path.resolve(gitDir, "info", "exclude")
    await fs.promises.mkdir(path.dirname(excludePath), { recursive: true })

    let existing = ""
    try {
      existing = await fs.promises.readFile(excludePath, "utf8")
    } catch (error) {
      if (!(error && error.code === "ENOENT")) {
        throw error
      }
    }

    const currentEntries = new Set(
      String(existing || "")
        .split(/\r?\n/)
        .map((line) => line.trim())
        .filter((line) => line.length > 0)
    )
    const missingEntries = LAUNCHER_GIT_EXCLUDE_ENTRIES.filter((entry) => !currentEntries.has(entry))
    if (missingEntries.length === 0) {
      return false
    }

    let append = ""
    if (existing.length > 0 && !existing.endsWith("\n")) {
      append += "\n"
    }
    append += `${missingEntries.join("\n")}\n`
    await fs.promises.appendFile(excludePath, append, "utf8")
    return true
  }

  const bootstrapLauncherInstructionFiles = async (rootPath) => {
    const targetPath = path.resolve(rootPath)
    await fs.promises.mkdir(targetPath, { recursive: true })

    const instructionBody = await buildLauncherInstructionBody()
    const writtenFiles = []
    if (instructionBody) {
      for (let i = 0; i < LAUNCHER_AGENT_FILES.length; i++) {
        const filename = LAUNCHER_AGENT_FILES[i]
        const destination = path.resolve(targetPath, filename)
        const created = await ensureLauncherAgentFile(destination, instructionBody)
        if (created) {
          writtenFiles.push(filename)
        }
      }
    }

    const geminiIgnoreCreated = await ensureGeminiIgnore(targetPath)
    if (geminiIgnoreCreated) {
      writtenFiles.push(".geminiignore")
    }

    await ensureGitExcludeEntries(targetPath)

    return {
      ok: true,
      files: writtenFiles
    }
  }

  return {
    bootstrapLauncherInstructionFiles,
    writeLauncherPromptContextFiles
  }
}

module.exports = {
  createLauncherInstructionBootstrap
}
